name: Deploy Frontend to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NodeJs Setup
        uses: actions/setup-node@v4
        with:
          node-version: [20.x]

      - name: Dependency Installation
        run: npm install

      - name: App build
        run: npm run build

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to AWS S3
        run: aws s3 sync build s3://dihive-dashboard --delete
