name: Deploy Node.js Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: |
          cd backEnd
          npm ci

      - name: Set up environment variables
        run: |
          cd backend
          touch .env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "AUTH_EMAIL=${{ secrets.AUTH_EMAIL }}" >> .env
          echo "AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
